export {
  LivenessResponseSchema,
  ReadinessResponseSchema,
  CoworkReadinessResponseSchema,
  HealthStatusSchema,
  DatabaseCheckSchema,
  HealthCheckResponseSchema,
  type LivenessResponse,
  type ReadinessResponse,
  type CoworkReadinessResponse,
  type HealthStatus,
  type DatabaseCheck,
  type HealthCheckResponse,
} from "./health.js";

export {
  ADMIN_BOOTSTRAP_USERNAME,
  ALL_STAFF_PERMISSIONS,
  AuthMeResponseSchema,
  AuthModeSchema,
  AuthSourceSchema,
  CentraleValidateSsoResponseSchema,
  CentraleValidatedUserSchema,
  GESTION_SESSION_COOKIE,
  LocalLoginRequestSchema,
  LogoutResponseSchema,
  NO_STAFF_PERMISSIONS,
  PrysmaEnrichmentSchema,
  SsoLoginRequestSchema,
  StaffPermissionsSchema,
  StaffProfilePublicSchema,
  StaffRoleSchema,
  PermissionsStaffRoleSchema,
  hasGestionAccess,
  StaffScopeSchema,
  type AuthMeResponse,
  type AuthMode,
  type AuthSource,
  type CentraleValidateSsoResponse,
  type CentraleValidatedUser,
  type LocalLoginRequest,
  type LogoutResponse,
  type PrysmaEnrichment,
  type SsoLoginRequest,
  type StaffPermissions,
  type StaffProfilePublic,
  type StaffRole,
  type PermissionsStaffRole,
  type StaffScope,
} from "./auth.js";

export {
  PERMISSIONS_PAGE_SIZES,
  PermissionsCompaniesResponseSchema,
  PermissionsPaginationSchema,
  PermissionsPageSizeSchema,
  PermissionsSecteursResponseSchema,
  PermissionsUserRowSchema,
  PermissionsUsersResponseSchema,
  PrysmaCompanyOptionSchema,
  PrysmaSecteurOptionSchema,
  type PermissionsCompaniesResponse,
  type PermissionsPagination,
  type PermissionsPageSize,
  type PermissionsSecteursResponse,
  type PermissionsUserRow,
  type PermissionsUsersResponse,
  type PrysmaCompanyOption,
  type PrysmaSecteurOption,
} from "./permissions.js";

export {
  WEEK_DAYS,
  BuildingAddressInputSchema,
  BuildingAddressResponseSchema,
  BuildingConciergeInputSchema,
  BuildingConciergeResponseSchema,
  BuildingCoordinatesResponseSchema,
  BuildingDayScheduleInputSchema,
  BuildingDayScheduleResponseSchema,
  BuildingFloorInputSchema,
  BuildingFloorResponseSchema,
  BuildingPhotoResponseSchema,
  BuildingResponseSchema,
  BuildingStatusSchema,
  BuildingsListResponseSchema,
  CreateBuildingRequestSchema,
  TIME_OF_DAY_SCHEMA,
  UpdateBuildingRequestSchema,
  BUILDING_DESCRIPTION_MAX_LENGTH,
  BuildingDescriptionSchema,
  normalizeCountryFromDb,
  normalizeCountryToDb,
  type BuildingAddressInput,
  type BuildingPhotoResponse,
  type BuildingResponse,
  type BuildingsListResponse,
  type CreateBuildingRequest,
  type UpdateBuildingRequest,
} from "./buildings.js";

export {
  BUILDING_PHOTO_STORAGE_KEY_PATTERN,
  DEFAULT_UPLOAD_MAX_BYTES,
  DEFAULT_UPLOAD_MAX_DIMENSION_PX,
  DEFAULT_UPLOAD_MAX_PHOTOS_PER_BUILDING,
  DEFAULT_UPLOAD_MAX_PHOTOS_PER_SPACE,
  ENTITY_PHOTO_STORAGE_KEY_PATTERN,
  UpdateBuildingPhotosRequestSchema,
  UpdateEntityPhotosRequestSchema,
  UPLOAD_ENTITY_TYPES,
  buildBuildingPhotoStorageKey,
  buildEntityPhotoStorageKey,
  buildSpacePhotoStorageKey,
  isValidBuildingPhotoStorageKey,
  isValidEntityPhotoStorageKey,
  isValidSpacePhotoStorageKey,
  mediaPathFromStorageKey,
  type UpdateBuildingPhotosRequest,
  type UpdateEntityPhotosRequest,
  type UploadEntityType,
} from "./uploads.js";

export {
  SEO_META_DESCRIPTION_MAX_LENGTH,
  buildSpaceSeoMeta,
  iterateSlugCandidates,
  resolveUniqueSlugFromSet,
  slugifySpaceName,
  type SpaceSeoMeta,
} from "./seo.js";

export {
  centsToEuros,
  computeTtcCents,
  eurosToCents,
  formatCentsAsEuroString,
  isValidEuroAmount,
} from "./money.js";

export {
  CreateSpaceRequestSchema,
  DEFAULT_SPACE_TARIFF_VAT_RATE,
  DURATION_CLASS_LABELS,
  MAX_SPACE_TARIFFS,
  SPACE_DESCRIPTION_MAX_LENGTH,
  SPACE_DURATION_CLASSES,
  SPACE_TYPES,
  SpaceAccessCodeSchema,
  SpaceDescriptionSchema,
  SpaceDurationClassSchema,
  SpaceEquipmentInputSchema,
  SpaceResponseSchema,
  SpaceSeoResponseSchema,
  SpaceStatusSchema,
  SpaceArchiveResponseSchema,
  SpaceOperationalStatusSchema,
  SpaceRestoreRequestSchema,
  SPACE_STATUSES,
  isSpaceArchived,
  SpaceTariffInputSchema,
  SpaceTariffResponseSchema,
  SpaceTypeSchema,
  SpacesListResponseSchema,
  UpdateSpaceRequestSchema,
  euroAmountSchema,
  mapTariffInputsToDb,
  type CreateSpaceRequest,
  type SpaceDurationClass,
  type SpaceResponse,
  type SpaceSeoResponse,
  type SpaceTariffInput,
  type SpaceTariffResponse,
  type SpacesListResponse,
  type SpaceArchiveResponse,
  type SpaceOperationalStatus,
  type SpaceRestoreRequest,
  type SpaceStatus,
  type UpdateSpaceRequest,
} from "./spaces.js";

export {
  DEFAULT_HOME_PUBLIC_CONTENT,
  DEFAULT_VITRINE_MARQUEE_TEXT,
  HomePublicContentSchema,
  UpdateVitrineContentRequestSchema,
  VITRINE_CONTENT_SINGLETON_ID,
  VITRINE_HERO_MAX_IMAGES,
  VITRINE_UPLOAD_MAX_BYTES,
  VITRINE_IMAGE_SLOTS,
  VITRINE_IMAGE_STORAGE_KEY_PATTERN,
  VitrineContentResponseSchema,
  VitrineMarqueeSchema,
  VitrineServiceImagesSchema,
  buildVitrineImageStorageKey,
  isValidVitrineImageStorageKey,
  mediaPathFromVitrineStorageKey,
  type HomePublicContent,
  type UpdateVitrineContentRequest,
  type VitrineContentResponse,
  type VitrineImageSlot,
  type VitrineMarquee,
  type VitrineServiceImages,
} from "./vitrine-content.js";
