export {
  LivenessResponseSchema,
  ReadinessResponseSchema,
  CoworkReadinessResponseSchema,
  HealthStatusSchema,
  DatabaseCheckSchema,
  HealthCheckResponseSchema,
  type LivenessResponse,
  type ReadinessResponse,
  type CoworkReadinessResponse,
  type HealthStatus,
  type DatabaseCheck,
  type HealthCheckResponse,
} from "./health.js";

export {
  ADMIN_BOOTSTRAP_USERNAME,
  ALL_STAFF_PERMISSIONS,
  AuthMeResponseSchema,
  AuthModeSchema,
  AuthSourceSchema,
  CentraleValidateSsoResponseSchema,
  CentraleValidatedUserSchema,
  GESTION_SESSION_COOKIE,
  LocalLoginRequestSchema,
  LogoutResponseSchema,
  NO_STAFF_PERMISSIONS,
  PrysmaEnrichmentSchema,
  SsoLoginRequestSchema,
  StaffPermissionsSchema,
  StaffProfilePublicSchema,
  StaffRoleSchema,
  PermissionsStaffRoleSchema,
  hasGestionAccess,
  StaffScopeSchema,
  type AuthMeResponse,
  type AuthMode,
  type AuthSource,
  type CentraleValidateSsoResponse,
  type CentraleValidatedUser,
  type LocalLoginRequest,
  type LogoutResponse,
  type PrysmaEnrichment,
  type SsoLoginRequest,
  type StaffPermissions,
  type StaffProfilePublic,
  type StaffRole,
  type PermissionsStaffRole,
  type StaffScope,
} from "./auth.js";

export {
  PERMISSIONS_PAGE_SIZES,
  PermissionsCompaniesResponseSchema,
  PermissionsPaginationSchema,
  PermissionsPageSizeSchema,
  PermissionsSecteursResponseSchema,
  PermissionsUserRowSchema,
  PermissionsUsersResponseSchema,
  PrysmaCompanyOptionSchema,
  PrysmaSecteurOptionSchema,
  type PermissionsCompaniesResponse,
  type PermissionsPagination,
  type PermissionsPageSize,
  type PermissionsSecteursResponse,
  type PermissionsUserRow,
  type PermissionsUsersResponse,
  type PrysmaCompanyOption,
  type PrysmaSecteurOption,
} from "./permissions.js";

export {
  WEEK_DAYS,
  BuildingAddressInputSchema,
  BuildingAddressResponseSchema,
  BuildingConciergeInputSchema,
  BuildingConciergeResponseSchema,
  BuildingCoordinatesResponseSchema,
  BuildingDayScheduleInputSchema,
  BuildingDayScheduleResponseSchema,
  BuildingFloorInputSchema,
  BuildingFloorResponseSchema,
  BuildingPhotoResponseSchema,
  BuildingResponseSchema,
  BuildingStatusSchema,
  BuildingsListResponseSchema,
  CreateBuildingRequestSchema,
  TIME_OF_DAY_SCHEMA,
  UpdateBuildingRequestSchema,
  BUILDING_DESCRIPTION_MAX_LENGTH,
  BUILDING_EMAIL_MAX_LENGTH,
  BUILDING_PHONE_MAX_LENGTH,
  BuildingDescriptionSchema,
  BuildingEmailSchema,
  BuildingPhoneSchema,
  SiteContactSchema,
  buildPhoneHref,
  normalizeOptionalBuildingContactField,
  normalizeCountryFromDb,
  normalizeCountryToDb,
  type BuildingAddressInput,
  type BuildingPhotoResponse,
  type BuildingResponse,
  type BuildingsListResponse,
  type CreateBuildingRequest,
  type SiteContact,
  type UpdateBuildingRequest,
} from "./buildings.js";

export { DEFAULT_SITE_CONTACT, resolveVitrineSiteContact } from "./site-contact.js";

export {
  PublicBuildingAddressSchema,
  PublicBuildingInfoSchema,
  DEFAULT_PUBLIC_BUILDING_INFO,
  buildGoogleMapsUrl,
  buildGoogleMapsDirectionsUrl,
  formatPublicBuildingAddress,
  mapDbBuildingToPublicInfo,
  type PublicBuildingAddress,
  type PublicBuildingInfo,
} from "./public-building-info.js";

export {
  BUILDING_PHOTO_STORAGE_KEY_PATTERN,
  DEFAULT_UPLOAD_MAX_BYTES,
  DEFAULT_UPLOAD_MAX_DIMENSION_PX,
  DEFAULT_UPLOAD_MAX_PHOTOS_PER_BUILDING,
  DEFAULT_UPLOAD_MAX_PHOTOS_PER_SPACE,
  ENTITY_PHOTO_STORAGE_KEY_PATTERN,
  UpdateBuildingPhotosRequestSchema,
  UpdateEntityPhotosRequestSchema,
  UPLOAD_ENTITY_TYPES,
  buildBuildingPhotoStorageKey,
  buildEntityPhotoStorageKey,
  buildSpacePhotoStorageKey,
  isValidBuildingPhotoStorageKey,
  isValidEntityPhotoStorageKey,
  isValidSpacePhotoStorageKey,
  mediaPathFromStorageKey,
  type UpdateBuildingPhotosRequest,
  type UpdateEntityPhotosRequest,
  type UploadEntityType,
} from "./uploads.js";

export {
  SEO_META_DESCRIPTION_MAX_LENGTH,
  buildSpaceSeoMeta,
  buildBuildingSeoMeta,
  iterateSlugCandidates,
  resolveUniqueSlugFromSet,
  slugifySpaceName,
  slugifyBuildingName,
  slugifyServiceKey,
  type SpaceSeoMeta,
} from "./seo.js";

export {
  centsToEuros,
  computeTtcCents,
  eurosToCents,
  formatCentsAsEuroString,
  isValidEuroAmount,
} from "./money.js";

export {
  CreateSpaceRequestSchema,
  DEFAULT_SPACE_TARIFF_VAT_RATE,
  DURATION_CLASS_LABELS,
  MAX_SPACE_TARIFFS,
  SPACE_DESCRIPTION_MAX_LENGTH,
  SPACE_DURATION_CLASSES,
  SPACE_TYPES,
  SpaceAccessCodeSchema,
  SpaceDescriptionSchema,
  SpaceDurationClassSchema,
  SpaceEquipmentInputSchema,
  SpaceResponseSchema,
  SpaceSeoResponseSchema,
  SpaceStatusSchema,
  SpaceArchiveResponseSchema,
  SpaceOperationalStatusSchema,
  SpaceRestoreRequestSchema,
  SPACE_STATUSES,
  isSpaceArchived,
  pickPrimaryPhotoStorageKey,
  SpaceTariffInputSchema,
  SpaceTariffResponseSchema,
  SpaceTypeSchema,
  SpacesListResponseSchema,
  UpdateSpaceRequestSchema,
  euroAmountSchema,
  mapTariffInputsToDb,
  type CreateSpaceRequest,
  type SpaceDurationClass,
  type SpaceResponse,
  type SpaceSeoResponse,
  type SpaceTariffInput,
  type SpaceTariffResponse,
  type SpacesListResponse,
  type SpaceArchiveResponse,
  type SpaceOperationalStatus,
  type SpaceRestoreRequest,
  type SpaceStatus,
  type SpaceType,
  type UpdateSpaceRequest,
} from "./spaces.js";

export {
  AboutPublicContentSchema,
  DEFAULT_ABOUT_PUBLIC_CONTENT,
  DEFAULT_HOME_PUBLIC_CONTENT,
  DEFAULT_VITRINE_MARQUEE_TEXT,
  HomePublicContentSchema,
  UpdateVitrineContentRequestSchema,
  VITRINE_CONTENT_SINGLETON_ID,
  VITRINE_FEATURED_BUILDINGS_MAX,
  VITRINE_FEATURED_SPACES_MAX,
  VITRINE_HERO_MAX_IMAGES,
  VITRINE_UPLOAD_MAX_BYTES,
  VITRINE_IMAGE_SLOTS,
  VITRINE_IMAGE_STORAGE_KEY_PATTERN,
  VitrineContentResponseSchema,
  VitrineMarqueeSchema,
  VitrineServiceImagesSchema,
  VitrineSiteContactSchema,
  VitrineSiteContactInputSchema,
  ServicesFeaturedSpaceSchema,
  ServicesPublicContentSchema,
  DEFAULT_SERVICES_PUBLIC_CONTENT,
  DEFAULT_SERVICES_FEATURED_SPACES,
  buildVitrineImageStorageKey,
  isValidVitrineImageStorageKey,
  mediaPathFromVitrineStorageKey,
  spaceTypeToVitrineHref,
  type AboutPublicContent,
  type HomePublicContent,
  type ServicesFeaturedSpace,
  type ServicesPublicContent,
  type UpdateVitrineContentRequest,
  type VitrineContentResponse,
  type VitrineImageSlot,
  type VitrineMarquee,
  type VitrineSiteContact,
  type VitrineServiceImages,
} from "./vitrine-content.js";

export {
  CatalogBuildingSummarySchema,
  CatalogBuildingDetailSchema,
  CatalogSpaceCardSchema,
  CatalogBuildingPageContentSchema,
  CatalogBuildingsListSchema,
  CatalogTariffLineSchema,
  CatalogTariffSpaceGroupSchema,
  CatalogTariffBuildingGroupSchema,
  CatalogTariffsContentSchema,
  computeStartingPriceHTCents,
  pickStartingPriceVatRate,
  durationClassLabel,
  type CatalogBuildingSummary,
  type CatalogBuildingDetail,
  type CatalogSpaceCard,
  type CatalogBuildingPageContent,
  type CatalogBuildingsList,
  type CatalogTariffLine,
  type CatalogTariffSpaceGroup,
  type CatalogTariffsContent,
} from "./catalog-content.js";

export {
  BOOKING_ERROR_CODES,
  BOOKING_PHASE1_DURATION_CLASSES,
  BookingAvailabilityQuerySchema,
  BookingAvailabilityResponseSchema,
  BookingErrorResponseSchema,
  BookingLockResponseSchema,
  BookingPhase1DurationClassSchema,
  type BookingPhase1DurationClass,
  BookingSlotSchema,
  BookingSpaceAvailabilityQuerySchema,
  BookingSpaceAvailabilityResponseSchema,
  BookingSpaceCardSchema,
  BookingSpacesQuerySchema,
  BookingSpacesResponseSchema,
  CreateBookingLockRequestSchema,
  ReleaseBookingLockQuerySchema,
  bookingDurationClassLabel,
  type BookingAvailabilityQuery,
  type BookingAvailabilityResponse,
  type BookingErrorCode,
  type BookingLockResponse,
  type BookingSlot,
  type BookingSpaceAvailabilityQuery,
  type BookingSpaceAvailabilityResponse,
  type BookingSpaceCard,
  type BookingSpacesQuery,
  type BookingSpacesResponse,
  type CreateBookingLockRequest,
} from "./booking.js";

export {
  DEFAULT_SERVICE_VAT_RATE,
  SERVICE_DESCRIPTION_MAX_LENGTH,
  SERVICE_LABEL_MAX_LENGTH,
  SERVICE_STATUSES,
  ServiceDescriptionSchema,
  ServiceResponseSchema,
  ServiceStatusSchema,
  ServicesListResponseSchema,
  CreateServiceRequestSchema,
  UpdateServiceRequestSchema,
  baseKeyForServiceLabel,
  mapCreateServiceRequestToDb,
  mapServicePriceDbToEuros,
  mapServicePriceEurosToDb,
  mapServiceToResponse,
  normalizeServiceDescription,
  resolveUniqueServiceKey,
  type CreateServiceRequest,
  type ServiceDbShape,
  type ServicePromoEligibility,
  type ServiceResponse,
  type ServiceStatus,
  type ServicesListResponse,
  type UpdateServiceRequest,
} from "./services.js";

export {
  MAX_SERVICE_CUSTOM_QUESTIONS,
  SERVICE_CUSTOM_QUESTION_LABEL_MAX_LENGTH,
  SERVICE_CUSTOM_QUESTION_SELECT_MIN_OPTIONS,
  SERVICE_CUSTOM_QUESTION_TYPE_LABELS,
  SERVICE_CUSTOM_QUESTION_TYPES,
  ServiceCustomAnswerSchema,
  ServiceCustomAnswerValueSchemas,
  ServiceCustomQuestionInputSchema,
  ServiceCustomQuestionSchema,
  ServiceCustomQuestionTypeSchema,
  ServiceCustomQuestionsInputSchema,
  ServiceCustomQuestionsSchema,
  ensureServiceCustomQuestionIds,
  mapServiceCustomQuestionsToResponse,
  normalizeServiceCustomQuestions,
  type ServiceCustomAnswer,
  type ServiceCustomQuestion,
  type ServiceCustomQuestionDbShape,
  type ServiceCustomQuestionInput,
  type ServiceCustomQuestionType,
  type ServiceCustomQuestions,
  type ServiceCustomQuestionsInput,
} from "./service-custom-questions.js";

export {
  DISCOUNT_APPLIES_TO,
  DISCOUNT_CODE_DISPLAY_STATUSES,
  DISCOUNT_CODE_KINDS,
  DISCOUNT_CODE_STATUSES,
  DISCOUNT_TYPES,
  PROMO_CODE_PATTERN,
  CreateDiscountCodeRequestSchema,
  DiscountAppliesToSchema,
  DiscountCodeKindSchema,
  DiscountCodeResponseSchema,
  DiscountCodeStatusSchema,
  DiscountCodeValidationError,
  DiscountCodesListResponseSchema,
  DiscountPerimeterInputSchema,
  DiscountPerimeterResponseSchema,
  DiscountTypeSchema,
  UpdateDiscountCodeRequestSchema,
  assertDiscountCodeServiceTargets,
  computeDiscountCodeDisplayStatus,
  mapDiscountCodeToResponse,
  mapDiscountValueToDb,
  mapFixedDiscountDbToEuros,
  mapFixedDiscountEurosToDb,
  type CreateDiscountCodeRequest,
  type DiscountAppliesTo,
  type DiscountCodeDbShape,
  type DiscountCodeDisplayStatus,
  type DiscountCodeKind,
  type DiscountCodeResponse,
  type DiscountCodeStatus,
  type DiscountCodeTargetInput,
  type DiscountCodesListResponse,
  type DiscountPerimeterInput,
  type DiscountType,
  type UpdateDiscountCodeRequest,
} from "./discount-codes.js";
